Repository BITNP/contest-bitnp, pull requests merged in 2023-08, with the labels that each got.

#80 feat(admin): Score filters
  contest/quiz/admin.py
Labels: type: feature, work: chaotic

#79 doc: Deploy
  contest/contest/settings.py
  doc/deploy.md
Labels: type: docs

#78 feat: 选择题和判断题在组卷时分别处理
  contest/quiz/admin.py
  contest/quiz/constants.py
  contest/quiz/migrations/0012_question_category.py
  contest/quiz/models.py
  contest/quiz/templates/contest.html
  contest/quiz/templates/index.html
  contest/quiz/templates/info.html
  contest/quiz/tests.py
  contest/quiz/views.py
  doc/models.md
  scripts/convert_problems_csv.py
Labels: type: feature, breaking, priority: soon, work: complex

#81 doc: more deploy doc
  DEVELOPMENT.md
  README.md
  doc/deploy.md
Labels: type: docs

#83 test: 答题次数超限后其它页面正常
  contest/quiz/tests.py
Labels: type: testing, work: obvious

#84 chore: 更改组卷要求
  contest/quiz/admin.py
  contest/quiz/constants.py
Labels: work: obvious, type: chore

#88 feat: 回顾答题记录
  contest/quiz/constants.py
  contest/quiz/templates/contest.html
  contest/quiz/templates/contest_review.html
  contest/quiz/templates/info.html
  contest/quiz/templatetags/current_page.py
  contest/quiz/tests.py
  contest/quiz/urls.py
  contest/quiz/util.py
  contest/quiz/views.py
Labels: type: feature, effort: 8, work: complicated

#82 feat: 竞赛开放时间
  Dockerfile
  README.md
  contest/contest/settings.py
  contest/quiz/admin.py
  contest/quiz/constants.py
  contest/quiz/tests.py
  contest/quiz/util.py
  contest/quiz/views.py
  doc/models.md
Labels: type: feature, effort: 5, work: complex

#87 fix: WebVPN
  contest/contest/settings.py
  contest/js/static_src/rollup.config.dev.mjs
  contest/js/static_src/rollup.config.prod.mjs
  contest/js/templatetags/__init__.py
  contest/js/templatetags/fallback_for_webvpn.py
  contest/quiz/templates/base.html
  doc/js.md
Labels: effort: 3, type: fix, work: chaotic

#90 ci: More lint rules
  contest/js/templatetags/fallback_for_webvpn.py
  contest/manage.py
  contest/quiz/admin.py
  contest/quiz/models.py
  contest/quiz/templatetags/current_page.py
  contest/quiz/tests.py
  contest/quiz/util.py
  contest/quiz/views.py
  pyproject.toml
  scripts/convert_md_fixture.py
Labels: effort: 1, type: testing, work: obvious, type: chore

#91 chore: 更改组卷要求
  contest/quiz/constants.py
Labels: effort: 1, work: obvious, type: chore

#92 fix: 回顾页窄屏题目卡片边距
  contest/quiz/templates/contest_review.html
Labels: effort: 2, work: obvious, type: fix

#97 chore: Update strings and constants
  contest/contest/settings.py
  contest/quiz/static/img/defense.png
  contest/quiz/static/img/remarks.yaml
  contest/quiz/templates/base.html
  contest/quiz/templates/index.html
Labels: effort: 2, priority: now, type: fix

#98 继续适配 WebVPN
  contest/js/templatetags/fallback_for_webvpn.py
  doc/js.md
Labels: work: obvious, effort: 3, type: fix
